'use client'

import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, ArrowUpRight, Bell, Cable, Check, ChevronDown, Clock3, Download, FileText, Gauge, LayoutDashboard, Menu, MoreHorizontal, Plus, RefreshCw, Router, Search, Settings, ShieldCheck, Signal, Ticket, Users, WalletCards, Wifi, X, Zap } from 'lucide-react'

type PageKey = 'overview' | 'router' | 'vouchers' | 'payments' | 'profiles' | 'settings'
type Connection = { mac: string; phone: string; ip: string; package: string; speed: string; time: string; since: string; status: string }

const navItems: { key: PageKey; label: string; icon: typeof LayoutDashboard }[] = [
  { key: 'overview', label: 'Dashboard Overview', icon: LayoutDashboard },
  { key: 'router', label: 'Router Controller', icon: Router },
  { key: 'vouchers', label: 'Voucher Generator', icon: Ticket },
  { key: 'payments', label: 'M-Pesa Ledger', icon: WalletCards },
  { key: 'profiles', label: 'Bandwidth Profiles', icon: Gauge },
  { key: 'settings', label: 'System Settings', icon: Settings },
]

const connections: Connection[] = [
  { mac: 'AA:BB:CC:12:34:56', phone: '0712•••678', ip: '10.10.10.21', package: '1 Hour Turbo', speed: '1 Mbps', time: '42m 18s', since: '12:43 PM', status: 'Online' },
  { mac: '3A:7F:91:22:AC:10', phone: '0798•••442', ip: '10.10.10.22', package: '3 Hours Stream', speed: '1.5 Mbps', time: '2h 11m', since: '11:20 AM', status: 'Online' },
  { mac: 'B4:21:8C:44:72:19', phone: '0701•••901', ip: '10.10.10.23', package: '24 Hour Unlimited', speed: '2 Mbps', time: '17h 42m', since: '09:31 AM', status: 'Online' },
]

const transactions = [
  { code: 'QK92H7T1XA', time: '26 Sep 2026 12:41', phone: '0712•••678', amount: 'KSh 10', package: '1 Hour Turbo', id: 'TXN-10291', status: 'Success' },
  { code: 'QK92H8R5MB', time: '26 Sep 2026 12:37', phone: '0798•••442', amount: 'KSh 20', package: '3 Hours Stream', id: 'TXN-10290', status: 'Success' },
  { code: '—', time: '26 Sep 2026 12:31', phone: '0701•••901', amount: 'KSh 50', package: '24 Hour Unlimited', id: 'TXN-10289', status: 'Failed' },
  { code: 'QK92H1A9KL', time: '26 Sep 2026 12:22', phone: '0722•••114', amount: 'KSh 10', package: '1 Hour Turbo', id: 'TXN-10288', status: 'Pending' },
]

function StatusBadge({ status }: { status: string }) {
  return <span className={`status-badge ${status.toLowerCase()}`}><span className="status-dot" />{status}</span>
}

function Sidebar({ page, setPage, mobileOpen, onClose }: { page: PageKey; setPage: (page: PageKey) => void; mobileOpen: boolean; onClose: () => void }) {
  return <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
    <div className="brand-row"><div className="brand-mark"><Wifi /></div><div><div className="brand-name">SYNTHNET</div><div className="brand-subtitle">BILLING ENGINE</div></div><button className="mobile-close" onClick={onClose} aria-label="Close navigation"><X /></button></div>
    <div className="sidebar-label">OPERATIONS</div>
    <nav className="nav-list">{navItems.map(({ key, label, icon: Icon }) => <button key={key} className={`nav-item ${page === key ? 'active' : ''}`} onClick={() => { setPage(key); onClose() }}><Icon /><span>{label}</span>{key === 'router' && <span className="nav-live-dot" />}</button>)}</nav>
    <div className="sidebar-spacer" /><div className="sidebar-label">SYSTEM STATUS</div>
    <div className="system-status"><div><span className="status-dot" />API Online</div><div><span className="status-dot" />Database Connected</div><div><span className="status-dot" />Router Tunnel Connected</div></div>
    <div className="sidebar-footer"><span>SynthNet Billing Engine</span><span>v1.0.0</span></div>
  </aside>
}

function Header({ title, onMenu }: { title: string; onMenu: () => void }) {
  return <header className="topbar"><div className="topbar-title"><button className="menu-button" onClick={onMenu} aria-label="Open navigation"><Menu /></button><div><div className="eyebrow">SYNTHNET / OPERATIONS</div><h1>{title}</h1></div></div><div className="topbar-actions"><div className="global-search"><Search /><input aria-label="Global search" placeholder="Search anything..." /></div><button className="icon-button notification" aria-label="Notifications"><Bell /><span /></button><div className="online-pill"><span className="status-dot" />All systems operational</div><div className="operator"><div className="avatar">AO</div><div className="operator-copy"><strong>Admin Operator</strong><span>Super Admin</span></div><ChevronDown /></div></div></header>
}

function MetricCard({ icon: Icon, label, value, detail, trend, tone = 'green' }: { icon: typeof Activity; label: string; value: string; detail: string; trend?: string; tone?: string }) {
  return <div className="metric-card"><div className="metric-top"><div className={`metric-icon ${tone}`}><Icon /></div>{trend && <span className="trend"><ArrowUpRight />{trend}</span>}</div><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div><div className={`metric-accent ${tone}`} /></div>
}

function Panel({ kicker, title, description, children, className = '' }: { kicker: string; title: string; description?: string; children: React.ReactNode; className?: string }) {
  return <section className={`panel ${className}`}><div className="panel-header"><div><div className="panel-kicker">{kicker}</div><h2>{title}</h2>{description && <p>{description}</p>}</div></div>{children}</section>
}

function ConnectionsPanel() {
  const [query, setQuery] = useState(''); const [disconnect, setDisconnect] = useState<Connection | null>(null)
  const rows = useMemo(() => connections.filter(item => Object.values(item).join(' ').toLowerCase().includes(query.toLowerCase())), [query])
  return <Panel kicker="REAL-TIME" title={`Live Connections ${connections.length}`} description="Customers currently connected to SynthNet." className="connections-panel"><div className="table-toolbar"><div className="table-search"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search MAC, phone, IP..." /></div><button className="outline-button"><Download />Export CSV</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>STATUS</th><th>CLIENT</th><th>NETWORK</th><th>PACKAGE</th><th>SPEED</th><th>TIME REMAINING</th><th>CONNECTED SINCE</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.mac}><td><StatusBadge status={row.status} /></td><td><strong className="mono">{row.mac}</strong><span>{row.phone}</span></td><td><strong className="mono">{row.ip}</strong><span>DHCP client</span></td><td><strong>{row.package}</strong><span>Prepaid access</span></td><td><strong>{row.speed}</strong><span>down / up</span></td><td><strong className="time-value">{row.time}</strong><span>remaining</span></td><td><span>{row.since}</span><span>Today</span></td><td><button className="disconnect-button" onClick={() => setDisconnect(row)}>Disconnect</button></td></tr>)}</tbody></table></div>{disconnect && <div className="modal-backdrop"><div className="confirm-modal"><button className="modal-close" onClick={() => setDisconnect(null)} aria-label="Close"><X /></button><div className="modal-icon danger"><AlertTriangle /></div><h3>Disconnect this client?</h3><p>This mocked action will queue a controlled disconnect for <strong>{disconnect.mac}</strong>.</p><div className="modal-details"><span>{disconnect.ip}</span><span>{disconnect.package}</span><span>{disconnect.time} remaining</span></div><div className="modal-actions"><button className="outline-button" onClick={() => setDisconnect(null)}>Cancel</button><button className="danger-button" onClick={() => setDisconnect(null)}>Disconnect Client</button></div></div></div>}</Panel>
}

function Overview() { return <><div className="page-intro"><div><div className="eyebrow">SATURDAY, 26 SEPTEMBER 2026 · 12:48 PM EAT</div><h2>Dashboard Overview</h2><p>Monitor your SynthNet network, payments, sessions, and gateway health.</p></div><button className="outline-button"><RefreshCw />Refresh data</button></div><div className="metrics-grid"><MetricCard icon={WalletCards} label="TOTAL REVENUE" value="KSh 48,750" detail="Compared to KSh 43,210 last month" trend="12.8%" /><MetricCard icon={Users} label="ACTIVE NETWORK USERS" value="24" detail="of 30 concurrent capacity" tone="purple" /><MetricCard icon={Activity} label="ACTIVE ONLINE SESSIONS" value="21" detail="3 sessions expiring soon" tone="blue" /><MetricCard icon={Signal} label="AIRTEL ODU GATEWAY" value="ONLINE" detail="Gateway healthy · 42 ms latency" /></div><Panel kicker="LIVE TELEMETRY" title="Network Usage" description="Bandwidth utilization across the SynthNet network." className="chart-panel"><div className="fake-chart"><span /><span /><span /><span /><span /><span /><span /></div><div className="chart-legend"><span><i className="legend-line download" />Download</span><span><i className="legend-line upload" />Upload</span><span><i className="legend-line users" />Active users</span></div></Panel><Panel kicker="FINANCIAL PERFORMANCE" title="Revenue Overview" description="Payment volume and revenue trend." className="revenue-panel"><div className="revenue-stats"><div><span>Today</span><strong>KSh 1,850</strong><small className="good-text">+8.4%</small></div><div><span>This week</span><strong>KSh 11,420</strong><small className="good-text">+12.1%</small></div><div><span>This month</span><strong>KSh 48,750</strong><small className="good-text">+12.8%</small></div><div><span>Transactions</span><strong>342</strong><small>successful payments</small></div></div></Panel><ConnectionsPanel /></> }

function RouterPage() { return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">INFRASTRUCTURE / ROUTEROS</div><h2>Router Controller</h2><p>Monitor and manage connected network infrastructure.</p></div><button className="primary-button"><RefreshCw />Sync router</button></div><Panel kicker="PRIMARY ROUTER · UI MOCK DATA" title="SYNTHNET-MT-01" description="MikroTik hEX RB750Gr3 · RouterOS 7.x"><div className="router-summary"><StatusBadge status="Online" /><div><span>UPTIME</span><strong>4d 17h 32m</strong></div><div><span>CPU</span><strong>18%</strong></div><div><span>MEMORY</span><strong>42%</strong></div><div><span>ACTIVE CLIENTS</span><strong>24 / 30</strong></div></div></Panel><Panel kicker="SECURE BRIDGE" title="Local Router CGNAT Tunnel" description="Outbound secure polling connection behind Airtel ODU/CGNAT."><div className="tunnel-grid"><div><span>STATUS</span><strong className="good-text">CONNECTED</strong></div><div><span>LAST HEARTBEAT</span><strong>8 seconds ago</strong></div><div><span>LATENCY</span><strong>43 ms</strong></div><div><span>COMMANDS PENDING</span><strong>0</strong></div></div></Panel><Panel kicker="CONTROLLED OPERATIONS" title="Router Command Queue" description="Structured commands waiting for the local bridge."><div className="empty-state"><Cable /><h3>No pending commands</h3><p>All structured router operations have been applied.</p></div></Panel></div> }

function VouchersPage() { const [generated, setGenerated] = useState(false); return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">REVENUE OPERATIONS / ACCESS</div><h2>Voucher Generator</h2><p>Create single or bulk prepaid access codes for customers.</p></div><button className="outline-button"><FileText />Batch history</button></div><Panel kicker="NEW ACCESS BATCH" title="Generate vouchers" description="Codes are created for controlled router authorization." className="generator-card"><label className="field-label">PACKAGE PROFILE<select><option>1 Hour Turbo · KSh 10 · 1 Mbps</option><option>3 Hours Stream · KSh 20 · 1.5 Mbps</option><option>24 Hour Unlimited · KSh 50 · 2 Mbps</option></select></label><div className="field-row"><label className="field-label">QUANTITY<input type="number" defaultValue="25" min="1" /></label><label className="field-label">PREFIX<input defaultValue="SYNTH" /></label><label className="field-label">CODE LENGTH<select defaultValue="8"><option>8 characters</option><option>10 characters</option></select></label></div><button className="primary-button full" onClick={() => setGenerated(true)}><Ticket />Bulk Generate Codes</button>{generated && <div className="success-alert"><Check /><span><strong>25 vouchers generated successfully.</strong><small>Batch SYN-260926-004 is ready to export.</small></span><button onClick={() => setGenerated(false)} aria-label="Dismiss"><X /></button></div>}</Panel><Panel kicker="RECENT VOUCHER BATCHES" title="Batch history" description="Track generated, redeemed, and available access codes."><div className="empty-state"><Zap /><h3>Ready for your next batch</h3><p>Generated batches will appear here with export and disable actions.</p></div></Panel></div> }

function PaymentsPage() { const [selected, setSelected] = useState<typeof transactions[number] | null>(null); return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">FINANCE / MPESA STK PUSH</div><h2>M-Pesa Transaction Ledger</h2><p>Monitor payment requests, callbacks, and transaction outcomes.</p></div><button className="outline-button"><Download />Export CSV</button></div><div className="summary-grid"><MetricCard icon={WalletCards} label="TODAY'S REVENUE" value="KSh 1,850" detail="Across 32 successful payments" /><MetricCard icon={Check} label="SUCCESSFUL PAYMENTS" value="32" detail="98.2% success rate" /><MetricCard icon={AlertTriangle} label="FAILED PAYMENTS" value="3" detail="Needs reconciliation" tone="amber" /><MetricCard icon={Clock3} label="PENDING STK REQUESTS" value="2" detail="Awaiting customer action" tone="purple" /></div><Panel kicker="PAYMENT EVENTS" title="Financial Ledger" description="Click a transaction to view its full callback timeline."><div className="data-table-wrap"><table className="data-table"><thead><tr><th>STATUS</th><th>M-PESA CODE</th><th>TIMESTAMP</th><th>PHONE</th><th>AMOUNT</th><th>PACKAGE</th><th>TRANSACTION ID</th></tr></thead><tbody>{transactions.map(tx => <tr key={tx.id} className="clickable-row" onClick={() => setSelected(tx)}><td><StatusBadge status={tx.status} /></td><td className="mono">{tx.code}</td><td>{tx.time}</td><td>{tx.phone}</td><td><strong>{tx.amount}</strong></td><td>{tx.package}</td><td className="mono">{tx.id}</td></tr>)}</tbody></table></div></Panel>{selected && <div className="modal-backdrop"><div className="confirm-modal"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close"><X /></button><div className="modal-icon"><WalletCards /></div><h3>Transaction {selected.id}</h3><p>{selected.package} · {selected.phone}</p><div className="timeline"><div><span />STK REQUESTED</div><div><span />CUSTOMER PROMPTED</div><div><span />{selected.status === 'Failed' ? 'PAYMENT FAILED' : 'PAYMENT CONFIRMED'}</div></div></div></div>}</div> }

function ProfilesPage() { const [open, setOpen] = useState(false); return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">NETWORK POLICY / QOS</div><h2>Bandwidth Profiles</h2><p>Manage package speed limits and network profiles.</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus />Create profile</button></div><Panel kicker="NETWORK CAPACITY" title="24 of 30 concurrent users active" description="Download 18.4 Mbps · Upload 6.2 Mbps · Average latency 42 ms." /><Panel kicker="ACCESS CONTROL" title="Active Profiles" description="Speed policies applied to prepaid sessions."><div className="data-table-wrap"><table className="data-table"><thead><tr><th>PROFILE</th><th>PACKAGE</th><th>DOWNLOAD</th><th>UPLOAD</th><th>DURATION</th><th>ACTIVE USERS</th><th>STATUS</th><th /></tr></thead><tbody>{[['Turbo', '1 Hour Turbo', '1 Mbps', '1 Mbps', '1 Hour', '8'], ['Stream', '3 Hours Stream', '1.5 Mbps', '1.5 Mbps', '3 Hours', '7'], ['Unlimited', '24 Hour Unlimited', '2 Mbps', '2 Mbps', '24 Hours', '9']].map(row => <tr key={row[0]}>{row.map((value, index) => <td key={value}><strong>{value}</strong></td>)}<td><StatusBadge status="Active" /></td><td><button className="icon-button"><MoreHorizontal /></button></td></tr>)}</tbody></table></div></Panel>{open && <div className="modal-backdrop"><div className="confirm-modal"><button className="modal-close" onClick={() => setOpen(false)} aria-label="Close"><X /></button><h3>Create bandwidth profile</h3><div className="settings-form"><label className="field-label">PROFILE NAME<input placeholder="Premium" /></label><label className="field-label">DOWNLOAD LIMIT<input placeholder="5 Mbps" /></label><label className="field-label">UPLOAD LIMIT<input placeholder="2 Mbps" /></label></div><div className="modal-actions"><button className="outline-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" onClick={() => setOpen(false)}>Save Profile</button></div></div></div>}</div> }

function SettingsPage() { const [tab, setTab] = useState('General'); return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">PLATFORM / CONFIGURATION</div><h2>System Settings</h2><p>Configure your SynthNet Billing Engine workspace.</p></div><button className="primary-button"><Check />Save changes</button></div><div className="settings-layout"><div className="settings-tabs">{['General', 'Network', 'Payments', 'Router', 'Vouchers', 'Security', 'Notifications'].map(item => <button key={item} className={tab === item ? 'selected' : ''} onClick={() => setTab(item)}>{item}</button>)}</div><Panel kicker={`${tab.toUpperCase()} SETTINGS`} title={`${tab} configuration`} description={`Manage the ${tab.toLowerCase()} preferences for your operator workspace.`}>{tab === 'General' ? <div className="settings-form"><label className="field-label">SYSTEM NAME<input defaultValue="SynthNet Billing Engine" /></label><label className="field-label">NETWORK NAME<input defaultValue="SynthNet" /></label><label className="field-label">SUPPORT CONTACT<input placeholder="support@synthnet.example" /></label><label className="field-label">TIMEZONE<select defaultValue="Africa/Nairobi"><option>Africa/Nairobi</option><option>UTC</option></select></label></div> : <div className="empty-state"><ShieldCheck /><h3>{tab} controls</h3><p>Sensitive credentials remain masked and protected.</p>{tab === 'Payments' && <div className="integration-status"><ShieldCheck /> M-Pesa integration <strong>Connected</strong></div>}</div>}</Panel></div></div> }

export default function SynthnetDashboard() { const [page, setPage] = useState<PageKey>('overview'); const [mobileOpen, setMobileOpen] = useState(false); const current = navItems.find(item => item.key === page); return <div className="app-shell"><Sidebar page={page} setPage={setPage} mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} /><div className="main-shell"><Header title={current?.label ?? 'Dashboard Overview'} onMenu={() => setMobileOpen(true)} /><main className="content-area">{page === 'overview' && <Overview />}{page === 'router' && <RouterPage />}{page === 'vouchers' && <VouchersPage />}{page === 'payments' && <PaymentsPage />}{page === 'profiles' && <ProfilesPage />}{page === 'settings' && <SettingsPage />}</main></div>{mobileOpen && <button className="mobile-overlay" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}</div> }
